version: '3'

services:
  auth:
    build: ./auth
    container_name: auth
    networks:
      - app-network

  notes:
    build: ./notes
    container_name: notes
    networks:
      - app-network

  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
