version: '3.8'

services:
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth
      - notes

  auth:
    build: ./auth
    volumes:
      - ./auth:/app
    environment:
      - FLASK_ENV=development

  notes:
    build: ./notes
    volumes:
      - ./notes:/app
    environment:
      - FLASK_ENV=development
